### ISSUE TITLE
Official install from repositories fail inputstream.ffmpegdirect

### ISSUE THREAD

**Issue by aldyl** [oleksis/plugin.video.picta#3]
![Captura de pantalla de 2022-09-13 18-03-55](https://user-images.githubusercontent.com/19227796/190017864-562c2df2-41d1-435d-89b6-4712dda9f9b3.png)

**Comment by aldyl** [comment]
[kodi.log](https://github.com/oleksis/plugin.video.picta/files/9561157/kodi.log)

**Comment by oleksis** [comment]
Testing from `Ubuntu 20.04.5 LTS (Focal Fossa)` the **Picta Video add-ons** work as expected. Try install the `VideoPlayer InputStream FFmpeg Direct 19.03` from `My add-ons`

- VideoPlayer InputStream

![Addons_VideoPlayer-InputStream_FFmpeg-Direct-19 03](https://user-images.githubusercontent.com/44526468/190047262-708f42b1-b607-476a-aca9-c7483321bdde.png)

- Dependencies

![Addons_Picta-2 1 0_Dependencies](https://user-images.githubusercontent.com/44526468/190047276-f3d236f1-4ad8-4772-96c3-95b9ed9d363b.png)

**Comment by aldyl** [comment]
I use official PPA of Kodi 

no Ubuntu-Debian Compilation

deb  https://ppa.launchpadcontent.net/team-xbmc/ppa/ubuntu focal  main 
#deb-src  https://ppa.launchpadcontent.net/team-xbmc/ppa/ubuntu main

i try install this package and work
sudo apt install kodi-inputstream-ffmpegdirect
